import '@/system/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AppThemeProvider from '@/components/providers/AppThemeProvider';
import ThemeChanger from '@/components/shared/ThemeChanger';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppThemeProvider>
          <div className="min-h-screen bg-th-background px-8 py-0">
            <div className="mx-auto flex w-full max-w-6xl flex-col justify-center px-8">
              <nav className="relative mx-auto flex w-full items-center justify-between border-gray-200 pb-8 pt-8 text-gray-900 dark:border-gray-700 sm:pb-16">
                <ThemeChanger />
              </nav>
              {children}
            </div>
          </div>
        </AppThemeProvider>
      </body>
    </html>
  );
}
