import "@/system/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppThemeProvider from "@/components/providers/AppThemeProvider";
import ThemeChanger from "@/components/shared/ThemeChanger";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppThemeProvider>
          <div className="py-0 px-8 bg-th-background min-h-screen">
            <div className="flex flex-col justify-center px-8 w-full max-w-6xl mx-auto">
              <nav className="relative flex items-center justify-between w-full pt-8 pb-8 mx-auto text-gray-900 border-gray-200 dark:border-gray-700 sm:pb-16">
                <ThemeChanger />
              </nav>
              {children}
            </div>
          </div>
        </AppThemeProvider>
      </body>
    </html>
  );
}
